// Code generated by smock; DO NOT EDIT.
package main

type RepositoryMock struct {
	HeadNameFunc           func() string
	HeadShortNameFunc      func() string
	RemoteEndpointHostFunc func() string
	RemoteEndpointPathFunc func() string
	RootDirectoryFunc 	   func() string
	LsRemoteFunc           func() (RefToHash, error)
}

func (m *RepositoryMock) HeadName() string {
	if m.HeadNameFunc == nil {
		panic("This method is not defined.")
	}
	return m.HeadNameFunc()
}

func (m *RepositoryMock) HeadShortName() string {
	if m.HeadShortNameFunc == nil {
		panic("This method is not defined.")
	}
	return m.HeadShortNameFunc()
}

func (m *RepositoryMock) RemoteEndpointHost() string {
	if m.RemoteEndpointHostFunc == nil {
		panic("This method is not defined.")
	}
	return m.RemoteEndpointHostFunc()
}

func (m *RepositoryMock) RemoteEndpointPath() string {
	if m.RemoteEndpointPathFunc == nil {
		panic("This method is not defined.")
	}
	return m.RemoteEndpointPathFunc()
}

func (m *RepositoryMock) RootDirectory() string {
	if m.RootDirectoryFunc == nil {
		panic("This method is not defined.")
	}
	return m.RootDirectoryFunc()
}

func (m *RepositoryMock) LsRemote() (RefToHash, error) {
	if m.LsRemoteFunc == nil {
		panic("This method is not defined.")
	}
	return m.LsRemoteFunc()
}
